### ISSUE TITLE
Struggling with serial connection with ESC

### ISSUE THREAD

**Issue by h-brenne** [JyeSmith/dshot-esc-tester#4]
I'm trying to make a thrust stand based on the dshot setup of this repo. I've got the excact same ESP32 module as described, and I'm using an Airbot Wraith32 V2. I've connected the telemetry signal to RX2, pin 16, and dshot signal to TX2, pin 17, and also ground from the battery to the ESP32. I've also tried other pin combinations and updated the hardwareserial setup. I've also tried another ESP32 and another ESC. Still, I can't seem to get any communication going.  The serial connection is only available when unplugging cables or powering the ESC, and no data is received. Do you have any idea what might be wrong?

**Comment by JyeSmith** [comment]
Check out the schematic below from the readme.  TLM connects to RX2 but the dshot signal wire connects to GPIO5.

https://easyeda.com/jyesmith/kv-meter

**Comment by h-brenne** [comment]
Thanks, works now!
